AADS, on Playground, when I fetch any object list, there is no limitation and can be output as a generator
kili-technology/kili-playground pull request #534
Opened 2022-04-13 20:03 UTC by theodu

- [ ] I opened a merge request on `kili` on a branch with the same name than the branch of the current pull request and forced security tests.
- [ ] I opened a pull request on the Node playground if the changes are breaking.

2022-04-14 10:13 UTC, PierreLeveau requested changes

2022-04-14 10:13 UTC, PierreLeveau commented on kili/queries/project/__init__.py
> +from kili.utils import row_generator_from_paginated_calls
-> `.utils`

2022-04-14 10:13 UTC, PierreLeveau commented on kili/queries/project/__init__.py
> +# warnings.filterwarnings("default", module='kili', category=DeprecationWarning)
rm comment

2022-04-15 13:01 UTC, PierreLeveau approved these changes

2022-04-15 13:02 UTC, PierreLeveau commented
note: I think there is an avenue for way more code factorization, but let's leave it like that for now.

2022-04-19 08:40 UTC, p-desaintchamas approved these changes

2022-04-19 10:53 UTC, merged