AADS, on the CLI, when I launch kili project describe, I have an easy-to-read project description
kili-technology/kili-playground pull request #583
Opened 2022-06-14 11:26 UTC by theodu

- [ ] I opened a merge request on `kili` on a branch with the same name than the branch of the current pull request and forced security tests.
- [ ] I opened a pull request on the Node playground if the changes are breaking.

2022-06-14 15:22 UTC, PierreLeveau requested changes
I suggest to change statistics to metrics (more widely adopted)

2022-06-14 15:22 UTC, PierreLeveau commented on kili/cli.py
> +    infos, dataset_statistics, quality_statistics = get_project_statistics(
`get_project_metrics` ?

2022-06-14 15:22 UTC, PierreLeveau commented on kili/queries/project/helpers.py
> +    """Get statisctics for a project.
typo

2022-06-17 13:54 UTC, theodu commented on kili/cli.py
> +    infos, dataset_statistics, quality_statistics = get_project_statistics(
Yes, i'll change that

2022-06-17 14:35 UTC, crsegerie commented on kili/cli.py
> +    """Show Analytics of a project.
cool command!

2022-06-20 07:52 UTC, theodu commented on kili/cli.py
> +              help='Id of the project to import assets in')
That is an excellent idea! I suggest to take it in the next command as there is still one command left to implement.

2022-06-20 08:42 UTC, crsegerie approved these changes

2022-06-20 09:20 UTC, PierreLeveau approved these changes

2022-06-20 09:21 UTC, merged